apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: todoapp-daemonset
  namespace: mateapp
  labels:
    app: todoapp-daemonset
spec:
  selector:
    matchLabels:
      app: todoapp-daemonset
  template:
    metadata:
      labels:
        app: todoapp-daemonset
    spec:
      containers:
      - name: todoapp-daemonset
        image: busyboxplus:curl
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
        args: 
        - /bin/sh
        - -c
        - |
          while true; do
            curl -s http://todoapp-service.todoapp.svc.cluster.local
            sleep 5
          done
